# Generated by Django 4.2.5 on 2023-10-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company',
            new_name='group',
        ),
    ]
