# Generated by Django 4.2.5 on 2023-10-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_company_client_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AMA', 'Andrew Moore and Associates'), ('CMA', 'CMA'), ('PIPECLAM', 'Pipeclam'), ('Unapproved', 'Unapproved')], default='Unapproved', max_length=10),
        ),
    ]
